spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/json_exporter?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
